apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-processor-config
  labels:
    app: payment-processor
data:
  SERVER_PORT: "8082"
  AZURE_QUEUE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite-emulator:10001/devstoreaccount1"
  AZURE_QUEUE_QUEUE_NAME: "orders-queue"
  AZURE_QUEUE_POLL_INTERVAL_MS: "5000"
  AZURE_BLOB_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite-emulator:10000/devstoreaccount1"
  AZURE_BLOB_CONTAINER_NAME: "audit"
  AZURE_COSMOS_ENDPOINT: "https://cosmosdb-emulator:8081"
  AZURE_COSMOS_KEY: "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
  AZURE_COSMOS_DATABASE_NAME: "payment-db"
  AZURE_COSMOS_CONTAINER_NAME: "transactions"
